name: CI
on:
  push:
    paths-ignore:
      - '.github/**'
      - 'demo/**'
      - 'docs/**'
      - '**.md'

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/bundler-audit@v1
    - uses: workarea-commerce/ci/rubocop@v1
    - uses: workarea-commerce/ci/eslint@v1
      with:
        args: '{admin,core,storefront}/{app,test}/**/*.js'
    - uses: workarea-commerce/ci/stylelint@v1
      with:
        args: '{admin,core,storefront}/{app,test}/**/*.scss'

  admin_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd admin && bin/rails test -b

  admin_system_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd admin && bin/rails test test/system/**/*_test.rb -b
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Admin Screenshots
        path: admin/test/dummy/tmp/screenshots

  core_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd core && bin/rails test test/**/*_test.rb -b

  storefront_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd storefront && bin/rails test -b

  storefront_system_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd storefront && bin/rails test test/system/**/*_test.rb -b
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Storefront Screenshots
        path: storefront/test/dummy/tmp/screenshots
