name: Docker Demo Image
on:
  release:
    types: [published]

jobs:
  image_build:
    name: Build, Tag & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
      - name: Build Image
        run: 'docker build -t demo_app demo/'
      - name: Tag & Push Version Image
        run: |
          VERSION_TAG=$(echo $GITHUB_REF | sed "s/.*\///")
          docker tag demo_app workarea/demo_app:$VERSION_TAG
          docker push workarea/demo_app:$VERSION_TAG
      - name: Tag & Push Latest Image
        run: |
          docker tag demo_app workarea/demo_app:latest
          docker push workarea/demo_app:latest
